### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by blasian** [worr/node-imdb-api#19]
I see one of your unofficial api has gone down, does that mean this will api no longer work as well?

**Comment by zettam** [comment]
Not working.

**Comment by blasian** [comment]
:(

**Comment by worr** [comment]
Unfortunately, it looks like the API was taken down, and there isn't currently a similar one.

I'll try and work on getting my own spun up, since I have the hosting capabilities.

**Comment by PsychoFox11** [comment]
Darn, just found this. That would be awesome if you got your own up. Need some kind of movie lookup for a personal project.

**Comment by rcdosado** [comment]
how did you subscribe to that api?thanks

**Comment by worr** [comment]
Being worked on in #22.
