### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by 110Percent** [worr/node-imdb-api#22]
Whenever I use `imdb.getReq({name: searchstring},callback)`, I get an error saying "SyntaxError: Unexpected end of input". What does this mean and how do I fix it?

**Comment by pchaigno** [comment]
> **What if one of the unofficial APIs disappears?**
File a bug. I'll get creative.

@worr Did you get a chance to look into this? It looks like a call for creativity :stuck_out_tongue_closed_eyes:

**Comment by brunsten** [comment]
+1

**Comment by worr** [comment]
I've started work on this already. What's in `master` currently works for just movies. Gonna tighten up tv shows in the next few days, and do a major version bump.

**Comment by worr** [comment]
Fixed by c537a0aa661fb4f355e0cb3dec4b803c25f53b14
