### ISSUE TITLE
ReferenceError: Can't find variable: require

### ISSUE THREAD

**Issue by devCram** [worr/node-imdb-api#25]
`var imdb = require("imdb-api");`

gives me the following error

`ReferenceError: Can't find variable: require`

My node is verison: v6.5.0

Any ideas? I just started using node.js. Maybe I got forgot a dependency?

**Comment by worr** [comment]
How are you running your code? In your browser or through node? This is a common error when people try and native node modules in the browser.

**Comment by devCram** [comment]
The code is working fine with node. I tried to run it through the browser. I now also now that I need something like browserify for this to work.

Thank you!
