### ISSUE TITLE
Doubts about Legal problems

### ISSUE THREAD

**Issue by Johnataa** [worr/node-imdb-api#29]
Hi, thank you for releasing this API.
I'm thinking about a project and i wanna know: can i have legal issues by using this API ?
I read this [page](http://www.imdb.com/help/show_leaf?usedatasoftware) and with my limited legal knowledge I think I'm not allowed to republish their database information.

Will I have legal problems ?

Thanks in advance.

**Comment by worr** [comment]
No, you should be fine. This just wraps omdb (despite the name), which has no such restrictions.
