### ISSUE TITLE
Need a bit of clarification

### ISSUE THREAD

**Issue by Happimir** [worr/node-imdb-api#32]
So this is the first time i am using an external api for my web project. I have used the install command listed and i am wondering how exactly does the process work for using this project? 

In my home directory I do have the the package.json, only dependencies it has is imdb-api:^2.2.0. 

To use this project, does our project have to be a node.js project? if so, how can I have it also look at the package.json file i have on my home directory? And if it does not need to be a node.js file, I would like to use it in my php code, how to do so? Apologies if this is not the correct place to ask this question.

**Comment by worr** [comment]
This is definitely targeted at node.js, but could be used in your frontend if you use one of the tools to do the packaging there (browserify or whatever is hip these days).

If you want to do this in your PHP backend, you probably want to find an equivalent module for PHP. I don't write PHP so I can't really help there. 🤷

**Comment by Happimir** [comment]
Gotcha, no problem. Thanks for the quick reply. Now if I did want to go the node.js route. I have webstorm, but I believe that it uses its own package.json or the default one from npm since if I do require('imdb-api') says it is not part of the dependency. Should I just manually edit that package.json file or is there a way to make it reference the one I have on my home directory?

**Comment by worr** [comment]
So `package.json` is a file that describes your application / module. It lists all the dependencies, and metadata for consumption by npm (or other theoretical package manager).

Your webapp will have its own `package.json`, which you could create with `npm init`. It sounds like webstorm might've created one for you? It's not an IDE that I use, so I'm not familiar with how it works. That said, in your app's `package.json`, you will list all of the dependencies that your app has. Then, when you use `npm` to build and test your app, it will handle pulling down your dependencies and your dependencies' dependencies, etc.
