### ISSUE TITLE
Auto Complete

### ISSUE THREAD

**Issue by upq** [worr/node-imdb-api#36]
Any ideas how I can fetch data to use for auto completion, since getting the data depends on a correctly spelling the show or the movie name.

Thanks. @worr

**Comment by worr** [comment]
I should implement searching in the near future, which should facilitate this.

**Comment by crystalfinch** [comment]
+1

**Comment by malux13** [comment]
+1

**Comment by worr** [comment]
I've added support for searching. Any type of fuzzy matching isn't supported by my downstream, so this is the best I can do at them moment,

Fixed by 67f6e771fc344b892b334fd028ce626c268e271a
