### ISSUE TITLE
Episode release date

### ISSUE THREAD

**Issue by jakestreb** [worr/node-imdb-api#40]
The episode releases seem to be off by 1 month.

I could be wrong, but it looks like the date constructor takes 0-11 for the month and it's given a parsed 1-12. (imdb.js line 26)

**Comment by AdeelK93** [comment]
That seems to resolve my issue as well, great catch! @jakestreb did you want to submit a PR?

**Comment by AdeelK93** [comment]
Submitted a PR #41

**Comment by worr** [comment]
Closed by e5127846b5cd3a2695a77b04c53d49e30568557b
