### ISSUE TITLE
Unable to resolve module 'os'

### ISSUE THREAD

**Issue by mwdossantos** [worr/node-imdb-api#42]
When getting the imdb object I get this error:

<img width="372" alt="screen shot 2017-03-27 at 12 03 21" src="https://cloud.githubusercontent.com/assets/8517723/24351305/7c8340fc-12e5-11e7-897d-e016a008b42f.png">

What does this mean, why is it happening and how can I fix it? I need this module for my app, it's for a school project and it's the only good imdb api out there.

Here's my project structure:

<img width="616" alt="screen shot 2017-03-27 at 12 06 21" src="https://cloud.githubusercontent.com/assets/8517723/24351407/d6e604da-12e5-11e7-86a8-f191c1570fac.png">

Thank you

**Comment by worr** [comment]
Hey,

You might want to look into this: https://github.com/PeelTechnologies/react-native-os

This isn't so much an issue with this app or its deps, it's that react-native doesn't provide an os module, which requests-promises relies on.
