### ISSUE TITLE
Cross origin issue

### ISSUE THREAD

**Issue by dweston03** [worr/node-imdb-api#44]
I'm attempting to try to pull in some data using the API and I keep receiving this error in my browser console.  

(index):1 XMLHttpRequest cannot load https://www.omdbapi.com/?plot=full&r=json&t=The%20Toxic%20Avengers. The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:3000' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

I'm using Meteor build tools and this is my exact code.  Any advice would be greatly appreciated.  

const imdb = require('imdb-api');
let movie='';

imdb.getReq({name:'The Toxic Avengers'}, (err,things) => {
	movie = things;
	console.log(movie);
});

**Comment by worr** [comment]
Sorry this took me longer than usual. I dismissed it as a server-side issue, and then realized that I was wrong and corrected it. I've pushed the correct code to master.
