### ISSUE TITLE
OMDB now needs a key!!

### ISSUE THREAD

**Issue by Rubberg** [worr/node-imdb-api#47]
Hi,
It seems your package does not work any more since omdb api now requests a private key.
"ERR IMDB: 401 - {"Response":"False","Error":"No API key provided."}"
Would you please update the package soon?

Thanks a lot!

**Comment by xerq** [comment]
I've created a [pull request for that issue](https://github.com/worr/node-imdb-api/pull/48), made changes that seem to work on my server.

**Comment by worr** [comment]
Closed via e9acf0b
