### ISSUE TITLE
Search Feature not working for year attribute.

### ISSUE THREAD

**Issue by dagmawim** [worr/node-imdb-api#54]
The 'search' function exposed by the imdb module does not filter based on year.

FIX 👍 : 
Go to imdb.ts (line 60-66). Inside method 'reqtoqueryobj'  under the condition to check if year is undefined, change **req**["y"] = req.year into **ret**["y"] = req.year. This will add the 'y' paramter to the return and not the request.

**Comment by worr** [comment]
Do you want to create a PR for this, since you have a comprehensive fix for this?
