### ISSUE TITLE
Documentation site is offline

### ISSUE THREAD

**Issue by pekadad** [worr/node-imdb-api#58]
I am trying to learn the capabilities of this API and followed the link to:

https://docs.worrbase.com/node/imdb-api/ 

But it is currently (as of about 5:30PM EST, 19 December 2017) returning an error.  It has been returning an error for about the last 30-60 minutes.

Attached image is what I see.  

![image](https://user-images.githubusercontent.com/31521091/34181988-71f28f24-e4e2-11e7-9c9f-1b563872763a.png)

**Comment by worr** [comment]
Thanks for the report; docs are back up
