### ISSUE TITLE
apiKey on each request?

### ISSUE THREAD

**Issue by sandro-pasquali** [worr/node-imdb-api#61]
Would it be possible to set the default apiKey on the omdb instance, such that it isn't necessary to send the key on each request? Maybe something like:

```
imdb.configure({ apiKey: 'foo' });
// allowing...
imdb.get('The Toxic Avenger', {timeout: 30000}) // No #apiKey necessary
```
Might also be good to allow setting other default config options (like `timeout`) this way (while enabling overrides on a per-call basis)

**Comment by worr** [comment]
I've fixed this in 085fa9a0641c00f905dfa5fbbe990cc4054e31d3, but the API is slightly different.

It looks like:

```js
const cli = new imdb.Client({ apiKey: 'foo' });
cli.get({name: 'The Toxic Avenger'});
```

This does work the way, where options get merged if you choose to add options to the `get` call.

I haven't cut the 4.0 release just yet, but it will be shipped once I've finished that up.

**Comment by sandro-pasquali** [comment]
Great!

**Comment by worr** [comment]
4.0.0 has been released. Hope that helps!
