### ISSUE TITLE
request is deprecated

### ISSUE THREAD

**Issue by SubJunk** [worr/node-imdb-api#71]
When installing this package we are presented with a notice that `request` is deprecated, see https://github.com/request/request/issues/3142
It's not an urgent thing but I thought it should have an issue.

**Comment by worr** [comment]
Thanks for the heads up! I'll reimplement this with the builtin `fetch` api in a later version.

**Comment by worr** [comment]
Fixed with 13eced02b9c4b76db8f778a9962c880751efacfa
