### ISSUE TITLE
Add `seriesid` to `Episode`

### ISSUE THREAD

**Issue by SubJunk** [worr/node-imdb-api#72]
I can see there are some nice TypeScript interfaces for different types of results, like `Episode` and `TVShow` as well as just `Movie`, but the `get` function's return type is `Promise<Movie>`, which means I get an error `Property 'episode' does not exist on type 'Movie'` if I do something like:

```
const imdbData = await imdbAPI.get({ id: imdbId });
const episode = imdbData.episode;
```

Is there some way around this?

**Comment by worr** [comment]
You can use `imdbData instanceof imdbAPI.TVShow` to check if it's a `imdbAPI.TVShow`. If used as a conditional, you don't need to actually do a cast:

```typescript
import * as imdb from 'imdb-api';

imdb.get({ name: "Dynasty" }, { apiKey: "189df455" }).then((mov) => {
    if (mov instanceof imdb.TVShow) {
        return mov.episodes();
    }
}).then((eps) => {
    console.log(eps);
    for (const ep in eps) {
        console.log(ep)
    }
}).catch((err) => {
    console.log(err);
});
```

**Comment by SubJunk** [comment]
@worr thanks, that works. A related question is that the `Episode` type doesn't include `seriesid` but the library returns it, can that be added to that type please?
My code:

```
  if (imdbData.type === 'episode' && imdbData instanceof Episode) {
    await EpisodeProcessing.create({ seriesimdbid: imdbData.seriesid });
```

Results in the error `Property 'seriesid' does not exist on type 'Episode'. Did you mean 'series'`

**Comment by worr** [comment]
Sure, I'll reopen and retitle this ticket to indicate it.

I have a wip branch right now that includes some major testing changes (you may have noticed recently that tests fail in the lib), but that's blocked on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45784. Once that's merged, I'll add this to the lib.

**Comment by SubJunk** [comment]
@worr thanks!
